--------------------------------------------------------
--  파일이 생성됨 - 금요일-12월-12-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_BOARD_NUM
--------------------------------------------------------

   CREATE SEQUENCE  "WEBPROJECT_DB"."SEQ_BOARD_NUM"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------

  CREATE TABLE "WEBPROJECT_DB"."BOARD" 
   (	"NUM" NUMBER, 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" VARCHAR2(2000 BYTE), 
	"ID" VARCHAR2(50 BYTE), 
	"POSTDATE" DATE DEFAULT sysdate, 
	"VISITCOUNT" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "WEBPROJECT_DB"."MEMBER" 
   (	"ID" VARCHAR2(50 BYTE), 
	"PASS" VARCHAR2(10 BYTE), 
	"NAME" VARCHAR2(30 BYTE), 
	"REGIDATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into WEBPROJECT_DB.BOARD
SET DEFINE OFF;
Insert into WEBPROJECT_DB.BOARD (NUM,TITLE,CONTENT,ID,POSTDATE,VISITCOUNT) values (2,'222','222','abc@abc.net',to_date('25/12/10','RR/MM/DD'),0);
Insert into WEBPROJECT_DB.BOARD (NUM,TITLE,CONTENT,ID,POSTDATE,VISITCOUNT) values (1,'111','111','abc@abc.net',to_date('25/12/10','RR/MM/DD'),0);
Insert into WEBPROJECT_DB.BOARD (NUM,TITLE,CONTENT,ID,POSTDATE,VISITCOUNT) values (4,'444','444','abc@abc.net',to_date('25/12/10','RR/MM/DD'),0);
Insert into WEBPROJECT_DB.BOARD (NUM,TITLE,CONTENT,ID,POSTDATE,VISITCOUNT) values (7,'qqqq','qqqq','abc@abc.net',to_date('25/12/12','RR/MM/DD'),0);
Insert into WEBPROJECT_DB.BOARD (NUM,TITLE,CONTENT,ID,POSTDATE,VISITCOUNT) values (9,'qqq','qq','abc@abc.net',to_date('25/12/12','RR/MM/DD'),0);
Insert into WEBPROJECT_DB.BOARD (NUM,TITLE,CONTENT,ID,POSTDATE,VISITCOUNT) values (6,'555','555','abc@abc.net',to_date('25/12/11','RR/MM/DD'),0);
Insert into WEBPROJECT_DB.BOARD (NUM,TITLE,CONTENT,ID,POSTDATE,VISITCOUNT) values (3,'222','222','abc@abc.net',to_date('25/12/10','RR/MM/DD'),0);
REM INSERTING into WEBPROJECT_DB.MEMBER
SET DEFINE OFF;
Insert into WEBPROJECT_DB.MEMBER (ID,PASS,NAME,REGIDATE) values ('abc@abc.net','aaaa','제갈공명',to_date('25/12/09','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index SYS_C008419
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008419" ON "WEBPROJECT_DB"."MEMBER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008430
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008430" ON "WEBPROJECT_DB"."BOARD" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008430
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008430" ON "WEBPROJECT_DB"."BOARD" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008419
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008419" ON "WEBPROJECT_DB"."MEMBER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."BOARD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD" MODIFY ("POSTDATE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."MEMBER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."MEMBER" MODIFY ("PASS" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."MEMBER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."MEMBER" MODIFY ("REGIDATE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."MEMBER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."BOARD" ADD CONSTRAINT "BOARD_MEM_FK" FOREIGN KEY ("ID")
	  REFERENCES "WEBPROJECT_DB"."MEMBER" ("ID") ENABLE;
